//
//  Data.swift
//  InfiniteScroll
//
//  Created by Amay Singhal on 10/6/15.
//  Copyright © 2015 ple. All rights reserved.
//

import Foundation

struct CaCities {

    static func getCitiesFromIndex(index: Int, andCount count: Int, withCompletion completion: ([String]?) -> ())  {

        // get the data from data source in background thread
        // do not perform any expensive processing function on main queue as it will make the UI unresponsive
        dispatch_async(dispatch_get_global_queue(QOS_CLASS_BACKGROUND, 0)) { () -> Void in
            var rangeStartIndex = index

            // handle start index out of bounds
            if rangeStartIndex < 0 {
                rangeStartIndex = 0
            } else if rangeStartIndex > CaCities.AllCities.endIndex {
                rangeStartIndex = CaCities.AllCities.endIndex
            }

            // handle end index out of bounds
            var rangeEndIndex = index + count
            if rangeEndIndex > CaCities.AllCities.endIndex {
                rangeEndIndex = CaCities.AllCities.endIndex
            }

            let nextCities = Array(CaCities.AllCities[rangeStartIndex..<rangeEndIndex])

            dispatch_async(dispatch_get_main_queue()) { () -> Void in
                completion(Array(nextCities))
            }
        }
    }

    static let AllCities = ["Anchorage, AK",
        "Fairbanks, AK",
        "Juneau, AK",
        "Fairbanks, AK",
        "Fairbanks, AK",
        "Anchorage, AK",
        "Fairbanks, AK",
        "Anchorage, AK",
        "Juneau, AK",
        "Fairbanks, AK",
        "Anchorage, AK",
        "Fairbanks, AK",
        "Anchorage, AK",
        "Fairbanks, AK",
        "Fairbanks, AK",
        "Anchorage, AK",
        "Juneau, AK",
        "Juneau, AK",
        "Fairbanks, AK",
        "Anchorage, AK",
        "Juneau, AK",
        "Juneau, AK",
        "Anchorage, AK",
        "Juneau, AK",
        "Juneau, AK",
        "Anchorage, AK",
        "Fairbanks, AK",
        "Fairbanks, AK",
        "Juneau, AK",
        "Anchorage, AK",
        "Anchorage, AK",
        "Fairbanks, AK",
        "Fairbanks, AK",
        "Anchorage, AK",
        "Juneau, AK",
        "Juneau, AK",
        "Anchorage, AK",
        "Anchorage, AK",
        "Juneau, AK",
        "Juneau, AK",
        "Anchorage, AK",
        "Fairbanks, AK",
        "Juneau, AK",
        "Fairbanks, AK",
        "Anchorage, AK",
        "Anchorage, AK",
        "Anchorage, AK",
        "Anchorage, AK",
        "Anchorage, AK",
        "Juneau, AK",
        "Juneau, AK",
        "Fairbanks, AK",
        "Anchorage, AK",
        "Anchorage, AK",
        "Anchorage, AK",
        "Dothan, AL",
        "Birmingham, AL",
        "Birmingham, AL",
        "Birmingham, AL",
        "Birmingham, AL",
        "Huntsville-Decatur (Florence), AL",
        "Montgomery (Selma), AL",
        "Birmingham, AL",
        "Birmingham, AL",
        "Birmingham, AL",
        "Montgomery (Selma), AL",
        "Birmingham, AL",
        "Huntsville-Decatur (Florence), AL",
        "Montgomery (Selma), AL",
        "Dothan, AL",
        "Birmingham, AL",
        "Birmingham, AL",
        "Huntsville-Decatur (Florence), AL",
        "Mobile, AL-Pensacola (Ft. Walton Beach), FL",
        "Birmingham, AL",
        "Columbus, GA",
        "Montgomery (Selma), AL",
        "Mobile, AL-Pensacola (Ft. Walton Beach), FL",
        "Mobile, AL-Pensacola (Ft. Walton Beach), FL",
        "Birmingham, AL",
        "Birmingham, AL",
        "Birmingham, AL",
        "Birmingham, AL",
        "Huntsville-Decatur (Florence), AL",
        "Birmingham, AL",
        "Mobile, AL-Pensacola (Ft. Walton Beach), FL",
        "Birmingham, AL",
        "Huntsville-Decatur (Florence), AL",
        "Mobile, AL-Pensacola (Ft. Walton Beach), FL",
        "Birmingham, AL",
        "Meridian, MS",
        "Birmingham, AL",
        "Montgomery (Selma), AL",
        "Birmingham, AL",
        "Birmingham, AL",
        "Birmingham, AL",
        "Montgomery (Selma), AL",
        "Birmingham, AL",
        "Huntsville-Decatur (Florence), AL",
        "Birmingham, AL",
        "Birmingham, AL",
        "Columbus, GA",
        "Columbus, GA",
        "Mobile, AL-Pensacola (Ft. Walton Beach), FL",
        "Dothan, AL",
        "Birmingham, AL",
        "Birmingham, AL",
        "Dothan, AL",
        "Dothan, AL",
        "Mobile, AL-Pensacola (Ft. Walton Beach), FL",
        "Huntsville-Decatur (Florence), AL",
        "Birmingham, AL",
        "Dothan, AL",
        "Mobile, AL-Pensacola (Ft. Walton Beach), FL",
        "Mobile, AL-Pensacola (Ft. Walton Beach), FL",
        "Montgomery (Selma), AL",
        "Huntsville-Decatur (Florence), AL",
        "Montgomery (Selma), AL",
        "Montgomery (Selma), AL",
        "Dothan, AL",
        "Birmingham, AL",
        "Montgomery (Selma), AL",
        "Dothan, AL",
        "Mobile, AL-Pensacola (Ft. Walton Beach), FL",
        "Dothan, AL",
        "Columbus, GA",
        "Birmingham, AL",
        "Mobile, AL-Pensacola (Ft. Walton Beach), FL",
        "Mobile, AL-Pensacola (Ft. Walton Beach), FL",
        "Birmingham, AL",
        "Mobile, AL-Pensacola (Ft. Walton Beach), FL",
        "Birmingham, AL",
        "Huntsville-Decatur (Florence), AL",
        "Mobile, AL-Pensacola (Ft. Walton Beach), FL",
        "Mobile, AL-Pensacola (Ft. Walton Beach), FL",
        "Montgomery (Selma), AL",
        "Huntsville-Decatur (Florence), AL",
        "Dothan, AL",
        "Mobile, AL-Pensacola (Ft. Walton Beach), FL",
        "Birmingham, AL",
        "Birmingham, AL",
        "Birmingham, AL",
        "Dothan, AL",
        "Montgomery (Selma), AL",
        "Birmingham, AL",
        "Birmingham, AL",
        "Mobile, AL-Pensacola (Ft. Walton Beach), FL",
        "Birmingham, AL",
        "Birmingham, AL",
        "Montgomery (Selma), AL",
        "Mobile, AL-Pensacola (Ft. Walton Beach), FL",
        "Birmingham, AL",
        "Mobile, AL-Pensacola (Ft. Walton Beach), FL",
        "Huntsville-Decatur (Florence), AL",
        "Birmingham, AL",
        "Birmingham, AL",
        "Birmingham, AL",
        "Huntsville-Decatur (Florence), AL",
        "Columbus, GA",
        "Birmingham, AL",
        "Montgomery (Selma), AL",
        "Huntsville-Decatur (Florence), AL",
        "Dothan, AL",
        "Atlanta, GA",
        "Birmingham, AL",
        "Huntsville-Decatur (Florence), AL",
        "Montgomery (Selma), AL",
        "Huntsville-Decatur (Florence), AL",
        "Mobile, AL-Pensacola (Ft. Walton Beach), FL",
        "Huntsville-Decatur (Florence), AL",
        "Dothan, AL",
        "Mobile, AL-Pensacola (Ft. Walton Beach), FL",
        "Birmingham, AL",
        "Birmingham, AL",
        "Montgomery (Selma), AL",
        "Birmingham, AL",
        "Huntsville-Decatur (Florence), AL",
        "Huntsville-Decatur (Florence), AL",
        "Columbus, GA",
        "Columbus, GA",
        "Birmingham, AL",
        "Birmingham, AL",
        "Mobile, AL-Pensacola (Ft. Walton Beach), FL",
        "Birmingham, AL",
        "Montgomery (Selma), AL",
        "Birmingham, AL",
        "Meridian, MS",
        "Columbus, GA",
        "Birmingham, AL",
        "Mobile, AL-Pensacola (Ft. Walton Beach), FL",
        "Montgomery (Selma), AL",
        "Huntsville-Decatur (Florence), AL",
        "Montgomery (Selma), AL",
        "Montgomery (Selma), AL",
        "Columbus-Tupelo-West Point, MS",
        "Mobile, AL-Pensacola (Ft. Walton Beach), FL",
        "Mobile, AL-Pensacola (Ft. Walton Beach), FL",
        "Mobile, AL-Pensacola (Ft. Walton Beach), FL",
        "Birmingham, AL",
        "Montgomery (Selma), AL",
        "Mobile, AL-Pensacola (Ft. Walton Beach), FL",
        "Birmingham, AL",
        "Huntsville-Decatur (Florence), AL",
        "Birmingham, AL",
        "Huntsville-Decatur (Florence), AL",
        "Dothan, AL",
        "Huntsville-Decatur (Florence), AL",
        "Dothan, AL",
        "Dothan, AL",
        "Birmingham, AL",
        "Montgomery (Selma), AL",
        "Birmingham, AL",
        "Birmingham, AL",
        "Columbus, GA",
        "Montgomery (Selma), AL",
        "Mobile, AL-Pensacola (Ft. Walton Beach), FL",
        "Birmingham, AL",
        "Dothan, AL",
        "Huntsville-Decatur (Florence), AL",
        "Birmingham, AL",
        "Birmingham, AL",
        "Meridian, MS",
        "Mobile, AL-Pensacola (Ft. Walton Beach), FL",
        "Columbus, GA",
        "Birmingham, AL",
        "Montgomery (Selma), AL",
        "Montgomery (Selma), AL",
        "Birmingham, AL",
        "Birmingham, AL",
        "Montgomery (Selma), AL",
        "Birmingham, AL",
        "Birmingham, AL",
        "Birmingham, AL",
        "Huntsville-Decatur (Florence), AL",
        "Montgomery (Selma), AL",
        "Huntsville-Decatur (Florence), AL",
        "Birmingham, AL",
        "Atlanta, GA",
        "Mobile, AL-Pensacola (Ft. Walton Beach), FL",
        "Huntsville-Decatur (Florence), AL",
        "Montgomery (Selma), AL",
        "Birmingham, AL",
        "Mobile, AL-Pensacola (Ft. Walton Beach), FL",
        "Huntsville-Decatur (Florence), AL",
        "Montgomery (Selma), AL",
        "Mobile, AL-Pensacola (Ft. Walton Beach), FL",
        "Huntsville-Decatur (Florence), AL",
        "Birmingham, AL",
        "Mobile, AL-Pensacola (Ft. Walton Beach), FL",
        "Birmingham, AL",
        "Columbus-Tupelo-West Point, MS",
        "Birmingham, AL",
        "Mobile, AL-Pensacola (Ft. Walton Beach), FL",
        "Birmingham, AL",
        "Birmingham, AL",
        "Birmingham, AL",
        "Montgomery (Selma), AL",
        "Mobile, AL-Pensacola (Ft. Walton Beach), FL",
        "Mobile, AL-Pensacola (Ft. Walton Beach), FL",
        "Huntsville-Decatur (Florence), AL",
        "Montgomery (Selma), AL",
        "Birmingham, AL",
        "Birmingham, AL",
        "Huntsville-Decatur (Florence), AL",
        "Montgomery (Selma), AL",
        "Montgomery (Selma), AL",
        "Columbus, GA",
        "Columbus-Tupelo-West Point, MS",
        "Birmingham, AL",
        "Atlanta, GA",
        "Birmingham, AL",
        "Birmingham, AL",
        "Dothan, AL",
        "Atlanta, GA",
        "Montgomery (Selma), AL",
        "Birmingham, AL",
        "Meridian, MS",
        "Huntsville-Decatur (Florence), AL",
        "Montgomery (Selma), AL",
        "Mobile, AL-Pensacola (Ft. Walton Beach), FL",
        "Montgomery (Selma), AL",
        "Montgomery (Selma), AL",
        "Birmingham, AL",
        "Huntsville-Decatur (Florence), AL",
        "Huntsville-Decatur (Florence), AL",
        "Huntsville-Decatur (Florence), AL",
        "Birmingham, AL",
        "Birmingham, AL",
        "Birmingham, AL",
        "Birmingham, AL",
        "Montgomery (Selma), AL",
        "Birmingham, AL",
        "Birmingham, AL",
        "Huntsville-Decatur (Florence), AL",
        "Huntsville-Decatur (Florence), AL",
        "Columbus, GA",
        "Birmingham, AL",
        "Mobile, AL-Pensacola (Ft. Walton Beach), FL",
        "Birmingham, AL",
        "Little Rock-Pine Bluff, AR",
        "Little Rock-Pine Bluff, AR",
        "Ft. Smith-Fayetteville-Springdale-Rogers, AR",
        "Little Rock-Pine Bluff, AR",
        "Little Rock-Pine Bluff, AR",
        "Little Rock-Pine Bluff, AR",
        "Memphis, TN",
        "Jonesboro, AR",
        "Shreveport, LA",
        "Little Rock-Pine Bluff, AR",
        "Little Rock-Pine Bluff, AR",
        "Ft. Smith-Fayetteville-Springdale-Rogers, AR",
        "Little Rock-Pine Bluff, AR",
        "Little Rock-Pine Bluff, AR",
        "Jonesboro, AR",
        "Little Rock-Pine Bluff, AR",
        "Ft. Smith-Fayetteville-Springdale-Rogers, AR",
        "Little Rock-Pine Bluff, AR",
        "Ft. Smith-Fayetteville-Springdale-Rogers, AR",
        "Springfield, MO",
        "Little Rock-Pine Bluff, AR",
        "Memphis, TN",
        "Ft. Smith-Fayetteville-Springdale-Rogers, AR",
        "Little Rock-Pine Bluff, AR",
        "Ft. Smith-Fayetteville-Springdale-Rogers, AR",
        "Little Rock-Pine Bluff, AR",
        "Little Rock-Pine Bluff, AR",
        "Jonesboro, AR",
        "Little Rock-Pine Bluff, AR",
        "Memphis, TN",
        "Little Rock-Pine Bluff, AR",
        "Little Rock-Pine Bluff, AR",
        "Little Rock-Pine Bluff, AR",
        "Little Rock-Pine Bluff, AR",
        "Little Rock-Pine Bluff, AR",
        "Jonesboro, AR",
        "Little Rock-Pine Bluff, AR",
        "Ft. Smith-Fayetteville-Springdale-Rogers, AR",
        "Little Rock-Pine Bluff, AR",
        "Jonesboro, AR",
        "Little Rock-Pine Bluff, AR",
        "Ft. Smith-Fayetteville-Springdale-Rogers, AR",
        "Little Rock-Pine Bluff, AR",
        "Springfield, MO",
        "Little Rock-Pine Bluff, AR",
        "Jonesboro, AR",
        "Monroe, LA-El Dorado, AR",
        "Little Rock-Pine Bluff, AR",
        "Little Rock-Pine Bluff, AR",
        "Shreveport, LA",
        "Little Rock-Pine Bluff, AR",
        "Ft. Smith-Fayetteville-Springdale-Rogers, AR",
        "Little Rock-Pine Bluff, AR",
        "Little Rock-Pine Bluff, AR",
        "Little Rock-Pine Bluff, AR",
        "Memphis, TN",
        "Monroe, LA-El Dorado, AR",
        "Ft. Smith-Fayetteville-Springdale-Rogers, AR",
        "Little Rock-Pine Bluff, AR",
        "Little Rock-Pine Bluff, AR",
        "Springfield, MO",
        "Little Rock-Pine Bluff, AR",
        "Ft. Smith-Fayetteville-Springdale-Rogers, AR",
        "Ft. Smith-Fayetteville-Springdale-Rogers, AR",
        "Springfield, MO",
        "Little Rock-Pine Bluff, AR",
        "Little Rock-Pine Bluff, AR",
        "Memphis, TN",
        "Monroe, LA-El Dorado, AR",
        "Little Rock-Pine Bluff, AR",
        "Ft. Smith-Fayetteville-Springdale-Rogers, AR",
        "Springfield, MO",
        "Ft. Smith-Fayetteville-Springdale-Rogers, AR",
        "Shreveport, LA",
        "Little Rock-Pine Bluff, AR",
        "Little Rock-Pine Bluff, AR",
        "Little Rock-Pine Bluff, AR",
        "Ft. Smith-Fayetteville-Springdale-Rogers, AR",
        "Little Rock-Pine Bluff, AR",
        "Ft. Smith-Fayetteville-Springdale-Rogers, AR",
        "Little Rock-Pine Bluff, AR",
        "Ft. Smith-Fayetteville-Springdale-Rogers, AR",
        "Monroe, LA-El Dorado, AR",
        "Jonesboro, AR",
        "Memphis, TN",
        "Springfield, MO",
        "Ft. Smith-Fayetteville-Springdale-Rogers, AR",
        "Little Rock-Pine Bluff, AR",
        "Little Rock-Pine Bluff, AR",
        "Little Rock-Pine Bluff, AR",
        "Little Rock-Pine Bluff, AR",
        "Little Rock-Pine Bluff, AR",
        "Shreveport, LA",
        "Little Rock-Pine Bluff, AR",
        "Little Rock-Pine Bluff, AR",
        "Jonesboro, AR",
        "Little Rock-Pine Bluff, AR",
        "Ft. Smith-Fayetteville-Springdale-Rogers, AR",
        "Jonesboro, AR",
        "Little Rock-Pine Bluff, AR",
        "Springfield, MO",
        "Little Rock-Pine Bluff, AR",
        "Memphis, TN",
        "Jonesboro, AR",
        "Memphis, TN",
        "Little Rock-Pine Bluff, AR",
        "Little Rock-Pine Bluff, AR",
        "Ft. Smith-Fayetteville-Springdale-Rogers, AR",
        "Springfield, MO",
        "Memphis, TN",
        "Little Rock-Pine Bluff, AR",
        "Little Rock-Pine Bluff, AR",
        "Little Rock-Pine Bluff, AR",
        "Shreveport, LA",
        "Little Rock-Pine Bluff, AR",
        "Little Rock-Pine Bluff, AR",
        "Ft. Smith-Fayetteville-Springdale-Rogers, AR",
        "Memphis, TN",
        "Jonesboro, AR",
        "Shreveport, LA",
        "Little Rock-Pine Bluff, AR",
        "Springfield, MO",
        "Ft. Smith-Fayetteville-Springdale-Rogers, AR",
        "Memphis, TN",
        "Memphis, TN",
        "Memphis, TN",
        "Jonesboro, AR",
        "Little Rock-Pine Bluff, AR",
        "Little Rock-Pine Bluff, AR",
        "Jonesboro, AR",
        "Little Rock-Pine Bluff, AR",
        "Little Rock-Pine Bluff, AR",
        "Little Rock-Pine Bluff, AR",
        "Little Rock-Pine Bluff, AR",
        "Little Rock-Pine Bluff, AR",
        "Little Rock-Pine Bluff, AR",
        "Little Rock-Pine Bluff, AR",
        "Monroe, LA-El Dorado, AR",
        "Little Rock-Pine Bluff, AR",
        "Little Rock-Pine Bluff, AR",
        "Little Rock-Pine Bluff, AR",
        "Springfield, MO"]
}